set -Ux XDG_DESKTOP_DIR "$HOME/desktop"
set -Ux XDG_DOWNLOAD_DIR "$HOME/downloads"
set -Ux XDG_TEMPLATES_DIR "$HOME/dcim/templates"
set -Ux XDG_PUBLICSHARE_DIR "$HOME/dcim/public"
set -Ux XDG_DOCUMENTS_DIR "$HOME/dcim/documents"
set -Ux XDG_MUSIC_DIR "$HOME/dcim/music"
set -Ux XDG_PICTURES_DIR "$HOME/dcim/pictures"
set -Ux XDG_VIDEOS_DIR "$HOME/dcim/videos"
